document.getElementById("history").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("culture").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("tradion").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("tourism").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("food").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("dress").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("languages").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("travel").addEventListener("click",()=>{
    window.open("")
})
document.getElementById("location").addEventListener("click",()=>{
    window.open("")
})
